import localFont from 'next/font/local'
import '../styles/globals.css'
import '../lib/fontawesome'

export const metadata = {
  title: 'Cdudium Website',
  description: 'Generated by Cudium Developers',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  )
}
